examples/catalog.yml, examples/user_guide/02_Data_Ingestion_with_Intake.ipynb, examples/user_guide/04_Machine_Learning.ipynb
https://anaconda.org/jsignell/02_data_ingestion_with_intake/notebook
https://anaconda.org/jsignell/04_machine_learning/notebook
=> Adding some content to data ingestion and machine learning stubs

examples/catalog.yml, examples/user_guide/03_Alignment_and_Preprocessing.ipynb
Rendered notebook https://anaconda.org/jsignell/03_alignment_and_preprocessing/notebook
=> Adding some initial material for Alignment and Preprocessing

examples/catalog.yml, examples/topics/Heat_and_Trees.ipynb
Minor changes to make this actually buildable and to document the changes to minimum version requirements for various packages.
=> Heat and trees

.travis.yml, environment.yml
=> Adding caching for travis and updating env to use s3

.travis.yml, dodo.py, examples/topics/Heat_and_Trees.ipynb, examples/topics/Walker_Lake.ipynb, examples/topics/landsat_spectral_clustering.ipynb, examples/tutorial/02_Data_Ingestion_with_Intake.ipynb, examples/tutorial/04_Resampling.ipynb, tox.ini
closes https://github.com/ContinuumIO/pyviz-nasa/issues/13
=> Getting all the notebooks running in tests and improving site

examples/tutorial/04_Resampling.ipynb
closes https://github.com/ContinuumIO/pyviz-nasa/issues/14
=> Adding exponential backoff to https examples

examples/catalog.yml
@jlstevens this will fix the issue you are seeing of
```python-traceback
355     def add_auth(self, request):
356         if self.credentials is None:
--> 357             raise NoCredentialsError
358         datetime_now = datetime.datetime.utcnow()
359         request.context['timestamp'] = datetime_now.strftime(SIGV4_TIMESTAMP)
NoCredentialsError: Unable to locate credentials
NoCredentialsError: Unable to locate credentials
```
=> Fixing storage auth

environment-dev.yml, environment.yml, tox.ini
To update a pre-existing env do:
`conda env update -f environment.yml -n <env-name>`
=> Adding tqdm to env

doc/tutorial/index.rst, examples/ai18.ipynb, examples/tutorial/02_Data_Ingestion_with_Intake.ipynb
=> Updating some of the tutorial

examples/catalog.yml, examples/data/.data_stubs/catalog.yml, examples/topics/Heat_and_Trees.ipynb, examples/tutorial/01_Data_Ingestion_with_Intake.ipynb, examples/tutorial/04_Resampling.ipynb
I have it depending on files straight from s3 with caching so that it only needs to happen once.
=> Getting rid of exponential backoff in resample

doc/README.md
I am still working on this but figured I'd throw up a PR so that people have access @jlstevens @jbednar
=> Adding to doc/README 

examples/tutorial/index.ipynb
Link on tutorial index was broken
=> Fixing link

examples/ai18.ipynb, examples/tutorial/02_Introduction_to_Visualization.ipynb
Some fixes (broken links, invalid HTML comment) and some new material for the introduction to visualization notebook.
=> Additions and tweaks

examples/tutorial/05_Machine_Learning.ipynb
The ML part now took 2 min rather than 6 or more
=> Making 05_Machine_Learning example smaller

.travis.yml
I messed up the checkout command in #72.
=> Fixing travis to do right checkout

examples/topics/Carbon_Flux.ipynb
Updating carbon flux to not reuse X, fixing empty plots, only declare one dashboard, make one hot encoding of season and use that instead of day of year.
=> Fixing carbon flux

examples/topics/Image_Classification.ipynb
* Improves the model architecture
* Added data augmentations (i.e. random rotations, flips, cropping)
* Adds a Keras callback to visualize the accuracy during training
* Added more explanations
=> Various improvements to Image Classifier example

environment.yml, examples/topics/Image_Classification.ipynb
=> Using s3 and new intake-xarray plugin

.travis.yml, doc/README.md, dodo.py, environment-dev.yml, environment.yml, tox.ini
- Updated env
- Made `doit test_all` include small data setup and cleanup
=> Update env to depend on latest releases

examples/topics/Landsat_Spectral_Clustering.ipynb, examples/topics/Walker_Lake.ipynb
There aren't too many magics to remove but I also want to update any use of `.opts` and `.options`.
=> Update all notebooks to use new HoloViews options API

doc/conf.py, doc/topics/index.rst, environment-dev.yml
This PR: 
- Adds link to grabcut
- Uses latest version of nbsite
- Updates copyright year
Once this is green I'll merge it, tag a dev release and then tag a real release.
=> Updating nbsite and adding grabcut link

doc/conf.py
@jlstevens @philippjfr 
I added the Google Analytics ID to the conf.py file.
=> Adding a Google Analytics ID

doc/conf.py
=> update the html theme to use sphinx_holoviz_theme
